micronaut:
  application:
    name: redweed
  server:
    port: 8888

rdf:
  dataset:
    location: "./data/tdb"
    type: "TDB2"
  namespaces:
    default: "http://example.org/redweed/"
    base: "http://redweed.local/"

endpoints:
  prometheus:
    sensitive: false