micronaut:
  application:
    name: redweed
  server:
    port: 8888
  security:
    enabled: true
    intercept-url-map:
      - pattern: /swagger/**
        access: [ isAnonymous() ]
      - pattern: /swagger-ui/**
        access: [ isAnonymous() ]
      - pattern: /v3/api-docs/**
        access: [ isAnonymous() ]
      - pattern: /rapidoc/**
        access: [ isAnonymous() ]
      - pattern: /redoc/**
        access: [ isAnonymous() ]
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

rdf:
  dataset:
    location: "./data/tdb"
    type: "TDB2"
  namespaces:
    default: "http://example.org/redweed/"
    base: "http://redweed.local/"

endpoints:
  prometheus:
    sensitive: false