name: Clojure CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Nix
      uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Run tests
      run: nix-shell --run "cd rwclj && clj -X:test"

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: rwclj/target/junit.xml
        if-no-files-found: error # 'warn' or 'ignore' are also available

    - name: Generate coverage report
      run: nix-shell --run "cd rwclj && clj -M:coverage"

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # Optional: if you have a private repo or need to specify
        files: ./rwclj/target/coverage/codecov.json # Path to the coverage report
        working-directory: ./rwclj # Specifies the directory where clojure files are, also where codecov.json is created relative to.
        fail_ci_if_error: true

    - name: Build uberjar (optional)
      run: nix-shell --run "cd rwclj && clj -M:uberjar"
