name: Jweed CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Shallow clones should be disabled for better SonarCloud analysis
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: 21
        distribution: temurin
    - name: Cache SonarCloud packages
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Validate Gradle wrapper
      uses: gradle/actions/wrapper-validation@v4
      with:
        working-directory: jweed
    - name: Build, test, and generate coverage report
      run: ./gradlew build jacocoTestReport
      working-directory: jweed
    - name: Display test results
      run: |
        echo "Test results:"
        find jweed/build/reports/tests -name "*.xml" -exec grep -H "testsuite" {} +
      working-directory: .
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: Test Reports
        path: |
          **/build/reports/tests/
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: Coverage Reports
        path: |
          **/build/reports/jacoco/
