name: PR Coverage Check

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Grant execute permission for gradlew
      run: chmod +x jweed/gradlew
    - name: Build with Gradle
      run: ./gradlew build
      working-directory: jweed
    - name: JaCoCo Report
      uses: madrapps/jacoco-report@v1.3
      with:
        paths: ${{ github.workspace }}/jweed/build/reports/jacoco/test/jacocoTestReport.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 40
        min-coverage-changed-files: 60
